import { NextRequest, NextResponse } from 'next/server'
import { requireApiAdmin } from '@/lib/auth'
import { generateVideoAccessToken } from '@/lib/video-access'
import { prisma } from '@/lib/db'
import { rateLimit } from '@/lib/rate-limit'
import { getConfiguredLocale, loadLocaleMessages } from '@/i18n/locale'
import { logError } from '@/lib/logging'


export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

/**
 * Admin Video Token Generation Endpoint
 *
 * Generates video access tokens for admin users to stream/download videos
 * Admins bypass normal share authentication but still need tokens for content delivery
 */
export async function GET(request: NextRequest) {
  const locale = await getConfiguredLocale().catch(() => 'en')
  const messages = await loadLocaleMessages(locale).catch(() => null)
  const videosMessages = messages?.videos || {}

  // Check authentication
  const authResult = await requireApiAdmin(request)
  if (authResult instanceof Response) {
    return authResult
  }

  // Rate limiting: Allow generous limit for token generation
  const rateLimitResult = await rateLimit(request, {
    windowMs: 60 * 1000,
    maxRequests: 200,
    message: videosMessages.tooManyTokenGenerationRequests || 'Too many token generation requests. Please slow down.'
  }, 'admin-video-token')

  if (rateLimitResult) {
    return rateLimitResult
  }

  try {
    const { searchParams } = new URL(request.url)
    const videoId = searchParams.get('videoId')
    const projectId = searchParams.get('projectId')
    const quality = searchParams.get('quality')
    const sessionId = searchParams.get('sessionId')

    if (!videoId || !projectId || !quality || !sessionId) {
      return NextResponse.json(
        { error: videosMessages.missingRequiredParameters || 'Missing required parameters' },
        { status: 400 }
      )
    }

    // Verify video belongs to project. Also pull the preview path
    // columns so we can short-circuit token issuance for tiers that
    // haven't been transcoded yet — see the quality-availability
    // gate below.
    const video = await prisma.video.findUnique({
      where: { id: videoId },
      select: {
        id: true,
        projectId: true,
        // 1.9.4+ Phase A: preview480Path is the new "fastest"
        // progressive tier. Casting via `as any` because the
        // Prisma client types need to be regenerated by
        // `npx prisma migrate dev` after the schema change —
        // the runtime select happily ignores unknown columns at
        // worst, but more importantly Postgres has the column
        // after migration.
        preview480Path: true,
        preview720Path: true,
        preview1080Path: true,
        preview2160Path: true,
      } as any,
    }) as any

    if (!video || video.projectId !== projectId) {
      return NextResponse.json(
        { error: videosMessages.videoNotFoundOrDoesNotBelongToProject || 'Video not found or does not belong to project' },
        { status: 404 }
      )
    }

    // 1.9.4+: with progressive multi-tier transcoding the higher
    // quality previews populate over time. If the caller asks for a
    // tier that doesn't exist yet, return an empty token instead of
    // a real one — the client then leaves the corresponding
    // streamUrl* slot empty so the player's "highest available"
    // selection (and the UI quality label) is honest. The content
    // endpoint's fallback chain still works for callers that pass
    // a real token but the file got deleted mid-flight.
    if (quality === '480p' && !video.preview480Path) {
      return NextResponse.json({ token: '' })
    }
    if (quality === '720p' && !video.preview720Path) {
      return NextResponse.json({ token: '' })
    }
    if (quality === '1080p' && !video.preview1080Path) {
      return NextResponse.json({ token: '' })
    }
    if (quality === '2160p' && !video.preview2160Path) {
      return NextResponse.json({ token: '' })
    }

    // Generate video access token
    const token = await generateVideoAccessToken(
      videoId,
      projectId,
      quality,
      request,
      sessionId
    )

    return NextResponse.json({ token })
  } catch (error) {
    logError('[API] Failed to generate admin video token:', error)
    return NextResponse.json(
      { error: videosMessages.failedToGenerateToken || 'Failed to generate token' },
      { status: 500 }
    )
  }
}
